export const COACH_PROFILE = [
  {
    id: 1,
    first_name: "Patrick Ian",
    last_name: "David",
    profilePic: "/coach/pat.jpg",
    phone: "09266864525",
    email: "pupufexdavid3@gmail.com",
    experience: 6,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
      instagram: "https://www.instagram.com/patrick_dvd/"
    },
    specialization: "Personal Training, Strength & Conditioning, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Powerlifting",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Powerlifting",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Powerlifter Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "3rd Place in National Equipped Powerlifting Championship in U93kg / Junior Category",
    certificates: "Sports Science Degree Holder at Bulacan State University",
  },
  {
    id: 2,
    first_name: "El John",
    last_name: "Aumentado",
    profilePic: "/coach/ej.jpeg",
    phone: "09171273175",
    email: "coach.ejja@gmail.com",
    experience: 12,
    social: {
      facebook: "https://www.facebook.com/share/1EzH4wW8GJ/?mibextid=wwXIfr"
    },
    specialization: "Personal Training, Strength & Conditioning, Weight Loss / Fat Loss, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Functional Training, Cardio Training, Nutrition & Diet Coaching, Flexibility & Mobility",
    philosophy: "I coach to help athletes grow in skill and character. I believe in hard work, teamwork, and always trying to improve in a positive and supportive way.",
    availability: "Weekdays",
    card_first_tier: "Bodybuilding / Muscle Gain",
    card_second_tier: "Weight Loss / Fat Loss",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Hypertrophy/Building Muscle Coach",
    card_second_subtier: "Nutrition & Diet Coaching",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "Natural Bodybuilding Australia 2024 Mens Fitness Pro Card, Natural Bodybuilding Australia 2024 Mens Fitness Overall Champion, Natural Bodybuilding Australia 2024 Mens Physique Open 2nd Place, Natural Bodybuilding Australia Mens Physique Novice 2nd Place, Young Slayer 2024 Mens Physique Natural 2nd Place, Get Wheysted Physique Athlete 2018, Mr. Bulacan Bodybuilding Athlete 2016",
    certificates: "NBA Universe PRO CARD, The Warriors Code Stage Ready Seminar Certification 2025, IFBB Fitnes Seminar and Posing Clinic Certification 2021",
  },
  {
    id: 3,
    first_name: "Timothy",
    last_name: "Ronquillo",
    profilePic: "/coach/tj.jpeg",
    phone: "09274083190",
    email: "Blanktzyy@gmail.com",
    experience: 4,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
    },
    specialization: "Personal Training, Strength & Conditioning, Weight Loss / Fat Loss, Cardio Training",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Personal Training",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Weight Loss / Fat Loss",
    card_first_subtier: "Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Body Recomposition Specialist",
    programsOffered: "Personal Training",
    employmentType: "Part-Time Coach",
  }
];

export const COACH_PROFILE_ABOUT = [
  {
    id: 1,
    first_name: "Patrick Ian",
    last_name: "David",
    profilePic: "/coach/pat.jpg",
    phone: "09266864525",
    email: "pupufexdavid3@gmail.com",
    experience: 6,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
      instagram: "https://www.instagram.com/patrick_dvd/"
    },
    specialization: "Personal Training, Strength & Conditioning, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Powerlifting",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Powerlifting",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Powerlifter Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "3rd Place in National Equipped Powerlifting Championship in U93kg / Junior Category",
    certificates: "Sports Science Degree Holder at Bulacan State University",
  },
  {
    id: 2,
    first_name: "El John",
    last_name: "Aumentado",
    profilePic: "/coach/ej.jpeg",
    phone: "09171273175",
    email: "coach.ejja@gmail.com",
    experience: 12,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
      instagram: "https://www.instagram.com/patrik_dvd/",
      youtube: "https://www.youtube.com/@EJJAFitness",
      tiktok: "https://www.tiktok.com/@ejja.fitness"
    },
    specialization: "Personal Training, Strength & Conditioning, Weight Loss / Fat Loss, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Functional Training, Cardio Training, Nutrition & Diet Coaching, Flexibility & Mobility",
    philosophy: "I coach to help athletes grow in skill and character. I believe in hard work, teamwork, and always trying to improve in a positive and supportive way.",
    availability: "Weekdays",
    card_first_tier: "Bodybuilding / Muscle Gain",
    card_second_tier: "Weight Loss / Fat Loss",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Hypertrophy/Building Muscle Coach",
    card_second_subtier: "Nutrition & Diet Coaching",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "Natural Bodybuilding Australia 2024 Men's Fitness Pro Card, Natural Bodybuilding Australia 2024 Men's Fitness Overall Champion, Natural Bodybuilding Australia 2024 Men's Physique Open 2nd Place, Natural Bodybuilding Australia Men's Physique Novice 2nd Place, Young Slayer 2024 Men's Physique Natural 2nd Place, Get Wheysted Physique Athlete 2018, Mr. Bulacan Bodybuilding Athlete 2016",
    certificates: "NBA Universe PRO CARD, The Warriors Code Stage Ready Seminar Certification 2025, IFBB Fitnes Seminar and Posing Clinic Certification 2021",
  },
  {
    id: 3,
    first_name: "Timothy",
    last_name: "Ronquillo",
    profilePic: "/coach/tj.jpeg",
    phone: "09274083190",
    email: "Blanktzyy@gmail.com",
    experience: 4,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
    },
    specialization: "Personal Training, Strength & Conditioning, Weight Loss / Fat Loss, Cardio Training",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Personal Training",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Weight Loss / Fat Loss",
    card_first_subtier: "Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Body Recomposition Specialist",
    programsOffered: "Personal Training",
    employmentType: "Part-Time Coach",
    achievements: "JDV Bodybuilding 2023 Men’s physique 1st Runner Up, IFBB Philippines Nationals 2023 Participant",
  },
  {
    id: 4,
    first_name: "Patrick Ian",
    last_name: "David",
    profilePic: "/pat.jpg",
    phone: "09266864525",
    email: "pupufexdavid3@gmail.com",
    experience: 6,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
      instagram: "https://www.instagram.com/patrik_dvd/"
    },
    specialization: "Personal Training, Strength & Conditioning, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Powerlifting",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Powerlifting",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Powerlifter Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "Sports Science Degree Holder at Bulacan State University, 3rd Place in National Equipped Powerlifting Championship in U93kg / Junior Category",
  },
  {
    id: 5,
    first_name: "Patrick Ian",
    last_name: "David",
    profilePic: "/pat.jpg",
    phone: "09266864525",
    email: "pupufexdavid3@gmail.com",
    experience: 6,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
      instagram: "https://www.instagram.com/patrik_dvd/"
    },
    specialization: "Personal Training, Strength & Conditioning, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Powerlifting",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Powerlifting",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Powerlifter Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "Sports Science Degree Holder at Bulacan State University, 3rd Place in National Equipped Powerlifting Championship in U93kg / Junior Category",
  },
  {
    id: 6,
    first_name: "Patrick Ian",
    last_name: "David",
    profilePic: "/pat.jpg",
    phone: "09266864525",
    email: "pupufexdavid3@gmail.com",
    experience: 6,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
      instagram: "https://www.instagram.com/patrik_dvd/"
    },
    specialization: "Personal Training, Strength & Conditioning, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Powerlifting",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Powerlifting",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Powerlifter Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "Sports Science Degree Holder at Bulacan State University, 3rd Place in National Equipped Powerlifting Championship in U93kg / Junior Category",
  },
  {
    id: 7,
    first_name: "Patrick Ian",
    last_name: "David",
    profilePic: "/pat.jpg",
    phone: "09266864525",
    email: "pupufexdavid3@gmail.com",
    experience: 6,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
      instagram: "https://www.instagram.com/patrik_dvd/"
    },
    specialization: "Personal Training, Strength & Conditioning, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Powerlifting",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Powerlifting",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Powerlifter Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "Sports Science Degree Holder at Bulacan State University, 3rd Place in National Equipped Powerlifting Championship in U93kg / Junior Category",
  },
  {
    id: 8,
    first_name: "Patrick Ian",
    last_name: "David",
    profilePic: "/pat.jpg",
    fitness_goal: "Weight Loss",
    height: "5'6\"",
    weight: "165 lbs",
    experience: 34,
    workout_days: 4,
    injuries: "Lower back pain",
    fitness_level: "Beginner",
    equipment_access: "Home gym",
    dietary_restrictions: "Lactose intolerant",
    workout_plan: {
      title: "Beginner Weight Loss Program",
      weekly_schedule: [
        { day: "Monday", focus: "Full Body Cardio", duration: "30 min" },
        { day: "Wednesday", focus: "Core & Lower Body", duration: "30 min" },
        { day: "Friday", focus: "HIIT Training", duration: "25 min" },
        { day: "Saturday", focus: "Active Recovery", duration: "40 min" },
      ],
      description:
        "This program focuses on building a consistent exercise habit with joint-friendly movements that protect your lower back. The mix of cardio and strength training supports weight loss while preserving muscle mass.",
    },
    diet_plan: {
      title: "Balanced Nutrition Plan (Lactose-Free)",
      daily_calories: "1,600 calories",
      macros: { protein: "30%", carbs: "40%", fats: "30%" },
      meal_examples: [
        { meal: "Breakfast", example: "Oatmeal with almond milk, berries, and chia seeds" },
        { meal: "Lunch", example: "Grilled chicken salad with olive oil dressing" },
        { meal: "Dinner", example: "Baked salmon with quinoa and roasted vegetables" },
        { meal: "Snacks", example: "Apple with almond butter, dairy-free yogurt with nuts" },
      ],
      description:
        "This meal plan avoids dairy products while providing balanced nutrition to support weight loss goals. Focus is on whole foods with adequate protein to preserve muscle during weight loss.",
    },
  },
  {
    id: 9,
    first_name: "Patrick Ian",
    last_name: "David",
    profilePic: "/pat.jpg",
    phone: "09266864525",
    email: "pupufexdavid3@gmail.com",
    experience: 6,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
      instagram: "https://www.instagram.com/patrik_dvd/"
    },
    specialization: "Personal Training, Strength & Conditioning, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Powerlifting",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Powerlifting",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Powerlifter Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "Sports Science Degree Holder at Bulacan State University, 3rd Place in National Equipped Powerlifting Championship in U93kg / Junior Category",
  },
  {
    id: 10,
    first_name: "Patrick Ian",
    last_name: "David",
    profilePic: "/pat.jpg",
    phone: "09266864525",
    email: "pupufexdavid3@gmail.com",
    experience: 6,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
      instagram: "https://www.instagram.com/patrik_dvd/"
    },
    specialization: "Personal Training, Strength & Conditioning, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Powerlifting",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Powerlifting",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Powerlifter Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "Sports Science Degree Holder at Bulacan State University, 3rd Place in National Equipped Powerlifting Championship in U93kg / Junior Category",
  },
  {
    id: 11,
    first_name: "Patrick Ian",
    last_name: "David",
    profilePic: "/pat.jpg",
    phone: "09266864525",
    email: "pupufexdavid3@gmail.com",
    experience: 6,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
      instagram: "https://www.instagram.com/patrik_dvd/"
    },
    specialization: "Personal Training, Strength & Conditioning, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Powerlifting",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Powerlifting",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Powerlifter Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "Sports Science Degree Holder at Bulacan State University, 3rd Place in National Equipped Powerlifting Championship in U93kg / Junior Category",
  },
  {
    id: 12,
    first_name: "Patrick Ian",
    last_name: "David",
    profilePic: "/pat.jpg",
    phone: "09266864525",
    email: "pupufexdavid3@gmail.com",
    experience: 6,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
      instagram: "https://www.instagram.com/patrik_dvd/"
    },
    specialization: "Personal Training, Strength & Conditioning, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Powerlifting",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Powerlifting",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Powerlifter Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "Sports Science Degree Holder at Bulacan State University, 3rd Place in National Equipped Powerlifting Championship in U93kg / Junior Category",
  },
  {
    id: 13,
    first_name: "Patrick Ian",
    last_name: "David",
    profilePic: "/pat.jpg",
    phone: "09266864525",
    email: "pupufexdavid3@gmail.com",
    experience: 6,
    social: {
      facebook: "https://www.facebook.com/patrick.ian.david.2024/",
      instagram: "https://www.instagram.com/patrik_dvd/"
    },
    specialization: "Personal Training, Strength & Conditioning, Bodybuilding / Muscle Gain, High-Intensity Interval Training (HIIT), Powerlifting",
    philosophy: "Fitness is a lifelong journey focused on overall health and enjoyment.",
    availability: "Everyday",
    card_first_tier: "Powerlifting",
    card_second_tier: "Bodybuilding / Muscle Gain",
    card_third_tier: "Strength & Conditioning",
    card_first_subtier: "Powerlifter Coach",
    card_second_subtier: "Hypertrophy/Building Muscle Coach",
    card_third_subtier: "Flexibility Movement Specialist",
    programsOffered: "Personal Training, Online Coaching",
    employmentType: "Freelance / Independent Contractor",
    achievements: "Sports Science Degree Holder at Bulacan State University, 3rd Place in National Equipped Powerlifting Championship in U93kg / Junior Category",
  },
];